export type { AdminAccountProfileData } from "./account";
export type {
  StudentAnalysisChatMessage,
  StudentAnalysisChatResponse,
  StudentAnalysisReport,
  StudentRiskLevel,
} from "./student-analysis";
export type {
  ClassTeacherAssignment,
  SubjectTeacherAssignment,
  AssignClassTeacherInput,
  AssignSubjectTeacherInput,
  UnassignSubjectTeacherInput,
  SubjectTeacherGap,
} from "./staffing";
export type {
  AdminAlert,
  AdminAlertSeverity,
  AdminDashboardData,
  AdminDashboardSnapshot,
  AdminQuickAction,
  AdminQuickActionType,
  LiveAttendanceSnapshot,
  LiveClassAttendance,
} from "./dashboard";
export type {
  AcademicYear,
  AdminSettings,
  AttendanceRulesSettings,
  FeatureToggle,
  InstitutionAddress,
  InstitutionInfoSettings,
  IntegrationSettings,
} from "./settings";
export type { CreateHolidayInput, Holiday, HolidayScope } from "./holidays";
export type {
  Announcement,
  AnnouncementChannel,
  AnnouncementTargetType,
  CreateAnnouncementInput,
} from "./announcements";
export { PIPELINE_STAGES } from "./admissions";
export type {
  Application,
  ApplicationDocument,
  AdmissionsData,
  ApplicationStatus,
  ArchivedBranchLink,
  CreateEnquiryInput,
  DuplicateEnrollmentWarning,
  EligibilityResult,
  EnrollmentProvisioning,
  FeeStructureSnapshot,
  ApplicantProfile,
  CourseEligibilityRule,
  Enquiry,
  EnquirySource,
  FunnelMetrics,
  MeritListEntry,
  RejectionInfo,
  PipelineStage,
  WizardProgress,
  NotificationRecipient,
  PipelineNotificationBatch,
} from "./admissions";
export type {
  AssignableRole,
  CreateUserInput,
  UpdateUserInput,
  InviteStatus,
  LinkedAccountSummary,
  ManagedUser,
  MultiRoleWarning,
  UserInvite,
  UserManagementData,
} from "./users";
export {
  TIMETABLE_TBD_SUBJECT_ID,
  TIMETABLE_UNASSIGNED_FACULTY_ID,
} from "./academics";
export type {
  AcademicsData,
  AcademicCalendarHoliday,
  CalendarPeriod,
  CalendarPeriodKind,
  ClassBatchSection,
  ClassSectionOption,
  CreateSubstitutionInput,
  DepartmentNode,
  FacultyOption,
  SubstitutionAvailability,
  RoomMaster,
  SaveCalendarPeriodInput,
  SaveClassSectionInput,
  SaveDepartmentInput,
  SaveSubjectInput,
  SaveTimetableSlotInput,
  StudyMaterial,
  SubjectMaster,
  SubstitutionRecord,
  SyllabusUnit,
  AdminReviewItem,
  AdminReviewItemType,
  CalendarChangeRecord,
  TimetableClash,
  TimetableClashType,
  TimetableSlot,
  TimetableSlotStatus,
  UpdateSyllabusCompletionInput,
  UploadStudyMaterialInput,
  WorkingDayRule,
} from "./academics";
export type {
  AttendanceAuditEntry,
  AttendanceAuditType,
  AttendanceData,
  AttendanceRecord,
  AttendanceStatus,
  AdminBulkMarkInput,
  AdminMarkAttendanceContext,
  AdminMarkAttendanceQuery,
  AdminMarkPeriodSlot,
  AdminMarkSubjectOption,
  CorrectAttendanceInput,
  CreateLeaveInput,
  LeaveRequest,
  LeaveRequestStatus,
  MonthlySubjectReportRow,
  MonthlyStudentReportRow,
  PeriodStudentReportRow,
  AttendanceReportFilters,
  AttendanceReportQuery,
  ReviewLeaveInput,
  StudentShortageRow,
} from "./attendance";
export type {
  ExamClash,
  ExamClashType,
  ArrearAttempt,
  ExamSlotWarning,
  ExamMarkEntry,
  ExamResultStatus,
  ExamFacultyOption,
  ExamRoomOption,
  ExamScheduleStatus,
  ExamSlot,
  ExamSummary,
  ExaminationsData,
  GraceMarksConfig,
  HallTicketResult,
  InvigilationAssignment,
  PdfExportResult,
  PublishedResultSnapshot,
  PublishedMarkEntry,
  ResultPublishConfirmation,
  ResultPublicationSummary,
  ResultsAnalytics,
  ResultsPreflightResult,
  ResultsSlotPreflight,
  ResultsConfig,
  SaveExamMarksInput,
  SaveExamMarksOptions,
  SaveExamSlotInput,
  SeatingAllocation,
  SeatingBulkError,
  SeatingGenerateMode,
  SeatingOrder,
  SeatingPlan,
  SeatingPreflightItem,
  SeatingPreflightResult,
  SeatingSession,
  StudentExamHubData,
  StudentExamProfile,
  StudentGpaMetric,
} from "./examinations";
export type {
  AutomatedAlertRule,
  AutomatedAlertType,
  CommsAudienceTarget,
  CommsAudienceTargetType,
  CommsChannel,
  CommsMessage,
  CommsPerRecipientStatus,
  CommsRecipientStatus,
  CommunicationsData,
  EmailTemplate,
  NotificationPreferences,
  UpdateNotificationChannelsInput,
  SendCommsMessageInput,
  SmsTemplate,
  TenantRateLimitState,
  UserFloodState,
} from "./communications";
export type {
  ActivityParticipation,
  CoCurricularActivity,
  DailyHomeworkEntry,
  HomeworkStatus,
  ParticipationStatus,
  PtmSchedule,
  PtmSlot,
  SaveActivityInput,
  SaveHomeworkInput,
  SaveParticipationInput,
  SavePtmInput,
  SchoolOnlyData,
} from "./school";
export type {
  CollegeElectiveRule,
  CollegeOnlyData,
  NaacNirfExportResult,
  SaveElectiveRuleInput,
  SaveElectiveSelectionInput,
  StudentElectiveSelection,
} from "./college";
export type {
  ApplyLeaveInput,
  CreatePayrollAdjustmentInput,
  HrBranch,
  HrBranchAdmin,
  HrComplianceExportResult,
  HrData,
  HrEmployeeDocument,
  HrEmployee,
  HrEmployeeBranchAssignment,
  HrEmploymentType,
  HrLeaveBalance,
  HrLeaveRequest,
  HrLeaveStatus,
  HrLeaveType,
  HrPayrollAdjustment,
  HrPayrollRun,
  HrPayslipPdfResult,
  HrReportExportResult,
  HrSalaryComponentTemplate,
  HrSalaryComponent,
  ReviewLeaveInputHr,
  RunPayrollInput,
  SaveSalaryTemplateInput,
  SaveAssignmentInput,
  SaveEmployeeInput,
} from "./hr";
export type {
  ConfirmTwinEnrollmentInput,
  StudentRegistryEntry,
} from "./students";
export type {
  GuardianManagementData,
  GuardianNotificationPrefs,
  GuardianRelationship,
  GuardianStudentSummary,
  SaveGuardianLinkInput,
  StudentGuardianLink,
} from "./guardians";
export type {
  AuditLogData,
  AuditLogDiffLine,
  AuditLogEntry,
  NaacExportPreview,
  NaacExportWithGapsResult,
  NaacFieldGap,
} from "./analytics";
export type {
  BulkImportFailedRow,
  BulkImportResult,
  ExportJob,
  ExportJobStatus,
  IncompleteProfileFlag,
  ReportDefinition,
  ReportModuleId,
  ReportSnapshotMeta,
  RolloverPreview,
  RolloverState,
  RolloverStudentPreview,
  SoftDeleteMeta,
} from "./platform-ops";
export type {
  ConcessionRequest,
  ConcessionRule,
  ConcessionStatus,
  CreditNote,
  CreditNoteRequest,
  ExamFeeInvoice,
  FeeCollectionSnapshot,
  FeeComponent,
  FeeComponentKind,
  FeePayment,
  FeePaymentsSummary,
  FeeStructure,
  FeesData,
  FeeBatchOption,
  StudentInstallmentScheduleRow,
  Installment,
  ReviewConcessionInput,
  ReviewRefundInput,
  RefundRequest,
  PaymentReconciliationItem,
  WebhookEventLog,
  RequestCreditNoteInput,
  ReviewCreditNoteInput,
  SaveConcessionRuleInput,
  SaveFeeStructureInput,
  StudentFeeLedgerRow,
} from "./fees";
