export { useAuth, useAuthStore } from './useAuth';
export { useRole } from './useRole';
export {
  useFacultyDashboard,
  useStudentDashboard,
  useAttendance,
  useAssignments,
  useGrades,
  useTimetable,
  useAnnouncements,
  useFacultyAttendanceSession,
  useFacultySchedule,
  useFacultyLeave,
  useFacultyStudyMaterial,
  useFacultyAssignmentsScreen,
  useFacultyAiTools,
  useFacultyMarksEntry,
  useFacultySyllabus,
  useFacultyInvigilation,
  useFacultySalary,
  useFacultyAlerts,
  useFacultyProfile,
  useFacultySettings,
  useFacultyHelpSupport,
} from './useData';
