export { useAuth, useAuthStore } from './useAuth';
export { useRole } from './useRole';
export {
  useFacultyDashboard,
  useStudentDashboard,
  useAttendance,
  useAssignments,
  useGrades,
  useTimetable,
  useStudentTimetable,
  useStudentLearn,
  useStudentMore,
  useStudentHomework,
  useStudentExams,
  useStudentFees,
  useStudentLeave,
  useStudentAlerts,
  useStudentNotices,
  useStudentProfile,
  useStudentHelpCenter,
  useAnnouncements,
  useFacultyAttendanceSession,
  useFacultySchedule,
  useFacultyLeave,
  useFacultyStudyMaterial,
  useFacultyAssignmentsScreen,
  useFacultyAiTools,
  useFacultyMarksEntry,
  useFacultySyllabus,
  useFacultyInvigilation,
  useFacultySalary,
  useFacultyAlerts,
  useFacultyProfile,
  useFacultySettings,
  useFacultyHelpSupport,
} from './useData';
