import type { StudentTimetableData } from '@piiaura/types';

const mondaySlots = [
  {
    id: 'mon-0900',
    kind: 'class' as const,
    startTime: '09:00',
    durationLabel: '105 min',
    subject: 'Engineering Mathematics I',
    category: 'core' as const,
    categoryLabel: 'Core',
    location: 'Block 3, Hall A',
    locationIcon: 'location' as const,
    facultyName: 'Dr. David Parker',
    facultyInitials: 'DP',
    isActive: true,
  },
  {
    id: 'mon-break',
    kind: 'break' as const,
    startTime: '10:45',
    breakLabel: 'Short Break',
  },
  {
    id: 'mon-1100',
    kind: 'class' as const,
    startTime: '11:00',
    durationLabel: '60 min',
    subject: 'Digital Electronics',
    category: 'lab' as const,
    categoryLabel: 'Lab',
    location: 'Lab 204, Tech Wing',
    locationIcon: 'science' as const,
    facultyName: 'Prof. Sarah Jenkins',
  },
  {
    id: 'mon-1200',
    kind: 'class' as const,
    startTime: '12:00',
    durationLabel: '60 min',
    subject: 'Professional Ethics',
    category: 'elective' as const,
    categoryLabel: 'Elective',
    location: 'Seminar Hall 1',
    locationIcon: 'room' as const,
    facultyName: 'Dr. Robert Chen',
  },
];

const tuesdaySlots = [
  {
    id: 'tue-0900',
    kind: 'class' as const,
    startTime: '09:00',
    durationLabel: '105 min',
    subject: 'Digital Electronics Lab',
    category: 'lab' as const,
    categoryLabel: 'Lab',
    location: 'Lab 204, Tech Wing',
    locationIcon: 'science' as const,
    facultyName: 'Prof. Sarah Jenkins',
  },
  {
    id: 'tue-break',
    kind: 'break' as const,
    startTime: '10:45',
    breakLabel: 'Short Break',
  },
  {
    id: 'tue-1100',
    kind: 'class' as const,
    startTime: '11:00',
    durationLabel: '60 min',
    subject: 'Engineering Mathematics II',
    category: 'core' as const,
    categoryLabel: 'Core',
    location: 'Block 3, Hall B',
    locationIcon: 'location' as const,
    facultyName: 'Dr. David Parker',
    facultyInitials: 'DP',
  },
  {
    id: 'tue-1200',
    kind: 'class' as const,
    startTime: '12:00',
    durationLabel: '60 min',
    subject: 'Engineering Graphics',
    category: 'elective' as const,
    categoryLabel: 'Elective',
    location: 'Design Studio 2',
    locationIcon: 'room' as const,
    facultyName: 'Prof. Anita Desai',
  },
];

export const mockStudentTimetableData: StudentTimetableData = {
  title: 'Timetable',
  days: [
    { id: 'mon-12', weekdayShort: 'Mon', dayNumber: 12 },
    { id: 'tue-13', weekdayShort: 'Tue', dayNumber: 13 },
    { id: 'wed-14', weekdayShort: 'Wed', dayNumber: 14 },
    { id: 'thu-15', weekdayShort: 'Thu', dayNumber: 15 },
    { id: 'fri-16', weekdayShort: 'Fri', dayNumber: 16 },
  ],
  selectedDayId: 'mon-12',
  dailySlotsByDay: {
    'mon-12': mondaySlots,
    'tue-13': tuesdaySlots,
    'wed-14': [
      {
        id: 'wed-1100',
        kind: 'class',
        startTime: '11:00',
        durationLabel: '60 min',
        subject: 'Digital Electronics',
        category: 'lab',
        categoryLabel: 'Lab',
        location: 'Lab 204, Tech Wing',
        locationIcon: 'science',
        facultyName: 'Prof. Sarah Jenkins',
      },
    ],
    'thu-15': [
      {
        id: 'thu-1100',
        kind: 'class',
        startTime: '11:00',
        durationLabel: '60 min',
        subject: 'Engineering Mathematics II',
        category: 'core',
        categoryLabel: 'Core',
        location: 'Block 3, Hall A',
        locationIcon: 'location',
        facultyName: 'Dr. David Parker',
        facultyInitials: 'DP',
      },
    ],
    'fri-16': [
      {
        id: 'fri-1100',
        kind: 'class',
        startTime: '11:00',
        durationLabel: '60 min',
        subject: 'Digital Electronics',
        category: 'lab',
        categoryLabel: 'Lab',
        location: 'Lab 204, Tech Wing',
        locationIcon: 'science',
        facultyName: 'Prof. Sarah Jenkins',
      },
    ],
  },
  showNowIndicator: true,
  nowIndicatorLabel: 'Now Happening',
  weeklyDayHeaders: ['MON', 'TUE', 'WED', 'THU', 'FRI'],
  weeklyRows: [
    {
      timeLabel: '09 AM',
      cells: [
        { code: 'MATH1', category: 'core' },
        { code: 'LAB_D', category: 'lab' },
        { code: 'MATH1', category: 'core' },
        { code: 'ETHIC', category: 'elective' },
        { code: 'MATH1', category: 'core' },
      ],
    },
    {
      timeLabel: '10 AM',
      cells: [
        { code: 'MATH1', category: 'core' },
        { code: 'LAB_D', category: 'lab' },
        null,
        { code: 'ETHIC', category: 'elective' },
        null,
      ],
    },
    {
      timeLabel: '11 AM',
      cells: [
        { code: 'DIGIT', category: 'lab' },
        { code: 'MATH2', category: 'core' },
        { code: 'DIGIT', category: 'lab' },
        { code: 'MATH2', category: 'core' },
        { code: 'DIGIT', category: 'lab' },
      ],
    },
    {
      timeLabel: '12 PM',
      cells: [
        { code: 'ETHIC', category: 'elective' },
        { code: 'ENGIN', category: 'elective' },
        null,
        { code: 'ENGIN', category: 'elective' },
        null,
      ],
    },
  ],
  legendTitle: 'Subject Legend',
  legend: [
    { id: 'core', label: 'Core Subjects', category: 'core' },
    { id: 'lab', label: 'Practical/Lab', category: 'lab' },
    { id: 'elective', label: 'Electives', category: 'elective' },
  ],
};
